[tool.poetry]
name = "pyrpc"
version = "0.1.0"
description = ""
authors = ["hujijun <hujijun@live.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
msgpack = "^1.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
